export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style = {{backgroundColor: "blue",
        padding: "1rem",}}>
          <p>International Used Auto Parts Inventory Manager</p>
          </header>
          {children}
         
          </body>
    </html>
  )
}
