export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style = {{backgroundColor: "blue",
        padding: "1rem",}}>
          <h1>International Used Auto Parts Inventory Manager</h1>
          </header>{children}
          <footer>Footer</footer>
          </body>
    </html>
  )
}
